name: Deploy to Server

on:
  push:
    branches:
      - feature/master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Development

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP (for Deployer CLI)
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install Deployer
        run: composer global require deployer/deployer

      # Deploy with SSH (trigger deployer.yml on server)
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/myTrek/current
            /home/deployer/.composer/vendor/bin/dep deploy staging -vvv
